---
title: "Combining_PretendPlay_Gesture"
author: "Kristen Johnson"
date: "2025-04-02"
output: html_document
---


```{r setup, include=FALSE}
#install.packages("extrafont")

library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(stringr)
library(knitr)
library(extrafont)  # Ensures Times New Roman is available
library(here)
```

# Reorganize Data for BI group
```{r}
# read in total data set create column for Group Status (P3=BI, P2=TD)
P3_H7_ALL <- read.csv(
  here("PN_Datasets", "Pretend_Play", "CSVs_of_Combined_Data_PP", "P3_H7_ALL.csv")
) %>%
  mutate(GroupStatus = "PL")

# ensure that all entries in c_form are in lower case
P3_H7_ALL$c_form <- tolower(P3_H7_ALL$c_form)

unique(P3_H7_ALL$c_form)
```

```{r}
# get rid of unnecessary columns & create necessary columns
P3_H7_Simple <- P3_H7_ALL %>% 
  select(participant_id, c_wpu, c_pret, c_form, line, GroupStatus)  %>% # Remove all but specific columns
  mutate(
    gesture_rep = if_else(c_form %in% c("point/iconic?", "iconic?", "iconic?~", "point - iconic", "iconic", "nod + iconic~", "point-iconic", "iconic~", "metaphoric", "demo"), 1, 0),
    gesture_all = if_else(!is.na(c_form) & c_form != "", 1, 0),
    gesture_icon = if_else(c_form %in% c("point/iconic?", "iconic?", "iconic?~", "point - iconic", "iconic", "nod + iconic~", "point-iconic", "iconic~"), 1, 0))
    
```

```{r}
names(P3_H7_Simple) <- tolower(names(P3_H7_Simple))
```



# Reorganize Data for TD group
```{r}
# read in total data set create column for Group Status (P3=BI, P2=TD)
P2_H7_ALL <- read.csv(here("PN_Datasets", "Pretend_Play", "CSVs_of_Combined_Data_PP", "H7", "P2_H7_ALL.csv")) %>%
  mutate(GroupStatus = "TD") # add column specifying which group this is
  
P2_H7_ALL$c_form <- tolower(P2_H7_ALL$c_form)
  
unique(P2_H7_ALL$c_form)
```

```{r}
# get rid of unnecessary columns & create necessary columns
P2_H7_Simple <- P2_H7_ALL %>% 
  select(participant_id, C_wpu, C_Pret, c_form, GroupStatus) %>%  # Remove all but specific columns
  mutate(
    gesture_rep = if_else(c_form %in% c("iconic", "iconic+shake", "beat-iconic-nod", "iconic~", "iconic-point", "iconic-iconic", "point~.iconic", "iconic - iconic", "iconic-iconic-cont palm", "palm-iconic", "iconic-iconic-iconic", "point~-iconic", "iconic ~", "point-iconic", "point-iconic-point", "demo", "metaphoric"), 1, 0),
    
    gesture_all = if_else(!is.na(c_form) & c_form != "", 1, 0),
    
    gesture_icon = if_else(c_form %in% c("iconic", "iconic+shake", "beat-iconic-nod", "iconic~", "iconic-point", "iconic-iconic", "point~.iconic", "iconic - iconic", "iconic-iconic-cont palm", "palm-iconic", "iconic-iconic-iconic", "point~-iconic", "iconic ~", "point-iconic", "point-iconic-point"), 1, 0)
  )
```

```{r}
# Make all column names lowercase
names(P2_H7_Simple) <- tolower(names(P2_H7_Simple))

```

# Combine Data from TD and BI kids to have complete year of data
```{r}
# Merge datasets by stacking them
merged_H7 <- bind_rows(P3_H7_Simple, P2_H7_Simple)

write.csv(merged_H7, here("PN_Datasets", "Pretend_Play", "CSVs_of_Combined_Data_PP", "merged_H7.csv"))
```

# Filter to include all utterances during pretend play
```{r}
# Filter to include only pretend play episodes
pretend_data_H7 <- merged_H7[merged_H7$c_pret == 1, ] 

head(pretend_data_H7)

write_csv(pretend_data_H7, here("PN_Datasets", "Pretend_Play", "CSVs_of_Combined_Data_PP", "pretend_data_H7.csv"))
```
# just pretend play with gesture
```{r}
alt_pretend_data_H7 <- merged_H7 %>%
  filter(c_pret == 1 & !is.na(c_form) & c_form != "")

```

```{r}

```

