---
title: "Interrater-Reliability_P3.93.10"
author: "Kristen Johnson"
date: "2025-03-04"
output:
  pdf_document: default
  html_document: default
---
# Load necessary libraries
```{r setup, echo=FALSE,include=FALSE}
library(readxl)   # For reading Excel files
library(dplyr)    # For binding and data manipulation
library(lubridate)  # For handling datetime columns (if needed)
library(tidyverse)  # to manipulate strings and a lot more
library(here)
```

# read in the two coded transcripts
```{r}
## be sure to change initials for each coder
#JB_codes<- read_excel(here("PN_InterraterReliability", "Coded_P3_H10", "P3.93.10_COMPLETE_JB_Final.xls"))

MCV_codes<- read_excel(here("PN_InterraterReliability", "Coded_P3_H10", "P3.150.10_COMPLETE_MCV_03.25.25.xls"))

KJ_codes <- read_excel(here("PN_InterraterReliability", "Coded_P3_H10", "For_Analysis", "P3.150.10_COMPLETE_KJ_Final.xls"))
```

# if need be, troubleshoot column name discrepancies
```{r}
# rename c_pret to lowercase only
#colnames(JB_codes)[colnames(JB_codes) == "C_pret_JB"] <- "c_pret_JB"

```

# get instances of pretend play (c_pret columns)
```{r, include=FALSE}
# get column names (to make sure c_pret is labelled right way)

#colnames(JB_codes)  # Returns column names as a character vector
colnames(MCV_codes)
colnames(KJ_codes)

# extract c_pret columns to get pretend play codes from each coder's transcript
#JB_codes <- JB_codes %>%  ## be sure to change initials for each coder!
  #select(C_pret_JB)

MCV_codes<- MCV_codes %>%
  select(C_pret_MCV)

KJ_codes <- KJ_codes %>%
  select(c_pret_KJ)
```

# combine datasets into one
```{r}
#coded_combined <- cbind(JB_codes, KJ_codes) ## be sure to change initials for each coder!
coded_combined <- cbind(MCV_codes, KJ_codes)
```

# create columns to assist in calculating IRR
```{r}
# create new columns for "both" and "either"
#coded_combined <- coded_combined %>%
  #mutate(
   # both_ones = ifelse(C_pret_JB == 1 & c_pret_KJ == 1, 1, 0), ## don't forget to change column names according to coder!
    #either_one = ifelse(C_pret_JB == 1 | c_pret_KJ == 1, 1, 0)
 # )
coded_combined <- coded_combined %>%
  mutate(
    both_ones = ifelse(C_pret_MCV == 1 & c_pret_KJ == 1, 1, 0),
    either_one = ifelse(C_pret_MCV == 1 | c_pret_KJ == 1, 1, 0)
  )
```

# make sure everything is numerical
```{r}
# change any NA value in both and either columns to 0
coded_combined[, c("both_ones", "either_one")] <- lapply(coded_combined[, c("both_ones", "either_one")], function(x) replace(x, is.na(x), 0))  # Multiple columns
```

# generate interrater reliability score
```{r}
# divide all instances of pretend play by overlap of pp instances
IRR_score <- sum(coded_combined$both_ones)/sum(coded_combined$either_one)

print(IRR_score)
```

