#Install packages for D2MR:
install.packages("citr")
install.packages("data.table")
install.packages("DescTools")
install.packages("ggsci")
install.packages("here")
install.packages("kableExtra")
install.packages("lme4")
install.packages("psych")
linstall.packages("quarto")
install.packages("RColorBrewer")
install.packages("Require")
install.packages("scales")
install.packages("stats")
install.packages("tidyverse")

# Load packages for D2MR:
library(citr)
library(data.table)
library(DescTools)
library(ggsci)
library(here)
library(kableExtra)
library(lme4)
library(psych)
library(quarto)
library(RColorBrewer)
library(Require)
library(scales)
library(stats)
library(tidyverse)
